camera_info:
  focal_length_x: 1345.200806
  focal_length_y: 1353.838257
  image_width: 800
  image_height: 600
view_distance: 30
model: 'udacity_trained_model_real'
stop_line_positions:
    - [8.0, 16.2]
